name: Publish crates
on:
  release:
    types: [published]

jobs:
  publish-simd-json-derive-int:
    name: Publish simd-json-derive-int
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish simd-json-derive-int to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: './simd-json-derive-int'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish-simd-json-derive:
    name: Publish simd-json-derive
    needs: publish-simd-json-derive-int
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish simd-json-derive to crates.io
        uses: katyo/publish-crates@v1
        with:
          path: '.'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}