name: "Publish Release"
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish Release from Tag
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ github.ref }}
    - name: Trigger publish crates workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Publish crates
        token: ${{ secrets.GITHUB_TOKEN }}